"""The Scotland view (site/scotland.html): constraint payments split by nation.

Every constraint payment in the bottom-up store is to a named wind BM unit. Which nation a
unit sits in comes from reference/bmu_zone.csv (regenerated by tools/build_bmu_zone.py from
Elexon's register: the unit's grid zone, from gspGroupId where Elexon fills it and otherwise
from the unit's transmission loss factor, which Elexon sets per zone). _P and _N are Scotland.

Who pays: constraint payments are recovered through balancing charges levied on electricity
consumed, so the share paid by Scottish consumers is Scotland's share of GB consumption
(reference/context.yaml: scotland_consumption_twh / gb_consumption_twh).
"""

from __future__ import annotations

import csv
from datetime import timedelta
from pathlib import Path

import polars as pl

# A constraint payment to a unit missing from bmu_zone.csv cannot be placed. Above this share
# of the window's total the build fails: re-run tools/build_bmu_zone.py.
MAX_UNPLACED_SHARE = 0.005
TOP_FARMS = 15


def load_bmu_zones(path: Path) -> dict[str, dict]:
    with Path(path).open(newline="") as f:
        rows = list(csv.DictReader(f))
    for r in rows:
        if not r.get("source_url"):
            raise ValueError(f"bmu_zone: {r['bmu']} has no source_url")
    return {r["bmu"]: r for r in rows}


def build_payload(con_daily: pl.DataFrame, zones: dict[str, dict], *,
                  scot_twh: float, gb_twh: float, consumption_source: str,
                  consumption_url: str, generated_at: str,
                  turnup_daily: pl.DataFrame | None = None) -> dict:
    """con_daily: the constraint store, one row per (date, bmu) — latest snapshot per date.
    turnup_daily: (date, cost_gbp) — the GB-wide estimate of what replacing switched-off wind
    cost (constraint_turnup.daily_cost). Not split by nation: it is not paid to named wind units."""
    nation = {b: z["nation"] for b, z in zones.items()}
    farm = {b: z["farm"] for b, z in zones.items()}
    df = con_daily.with_columns(
        pl.col("bmu").replace_strict(nation, default=None).alias("nation"),
        pl.col("bmu").replace_strict(farm, default=None).alias("farm"),
    )
    total = float(df["cost_gbp"].sum())
    unplaced = df.filter(pl.col("nation").is_null())
    unplaced_cost = float(unplaced["cost_gbp"].sum())
    if total and unplaced_cost / total > MAX_UNPLACED_SHARE:
        units = unplaced["bmu"].unique().sort().to_list()
        raise ValueError(
            f"scotland: £{unplaced_cost:,.0f} of constraint payments ({unplaced_cost / total:.1%}) "
            f"is to units missing from bmu_zone.csv {units[:10]} — run tools/build_bmu_zone.py")

    scot = df.filter(pl.col("nation") == "Scotland")
    scot_cost = float(scot["cost_gbp"].sum())
    scot_mwh = float(-scot["volume_mwh"].sum())
    end = df["date"].max()
    start = df["date"].min()
    last12 = scot.filter(pl.col("date") > end - timedelta(days=365))
    gb12 = df.filter(pl.col("date") > end - timedelta(days=365))

    farms = (scot.group_by("farm")
             .agg(pl.col("cost_gbp").sum().alias("cost"),
                  (-pl.col("volume_mwh").sum()).alias("mwh"),
                  pl.col("bmu").unique().sort().alias("units"))
             .sort("cost", descending=True))
    monthly = (df.with_columns(pl.col("date").dt.strftime("%Y-%m").alias("month"))
               .group_by("month")
               .agg(pl.col("cost_gbp").filter(pl.col("nation") == "Scotland").sum().alias("scotland"),
                    pl.col("cost_gbp").filter(pl.col("nation") != "Scotland").sum().alias("rest"))
               .sort("month"))

    share_consumption = scot_twh / gb_twh
    return {
        "generated_at": generated_at,
        "window": {"from": start.isoformat(), "to": end.isoformat()},
        "gb_cost": round(total, 2),
        "scotland_cost": round(scot_cost, 2),
        "scotland_share": round(scot_cost / total, 4) if total else 0.0,
        "scotland_mwh": round(scot_mwh),
        "gb_mwh": round(float(-df["volume_mwh"].sum())),
        "scotland_last12_cost": round(float(last12["cost_gbp"].sum()), 2),
        "gb_last12_cost": round(float(gb12["cost_gbp"].sum()), 2),
        "scotland_per_mwh": round(scot_cost / scot_mwh, 2) if scot_mwh else None,
        "unplaced_cost": round(unplaced_cost, 2),
        "n_farms_paid": farms.height,
        "farms": [{"farm": r["farm"], "cost": round(r["cost"], 2), "mwh": round(r["mwh"]),
                   "units": r["units"]} for r in farms.head(TOP_FARMS).to_dicts()],
        "top_farms_share": round(float(farms.head(TOP_FARMS)["cost"].sum()) / scot_cost, 4)
        if scot_cost else 0.0,
        "monthly": [{"month": r["month"], "scotland": round(r["scotland"]), "rest": round(r["rest"])}
                    for r in monthly.to_dicts()],
        "who_pays": {
            "scotland_consumption_twh": scot_twh,
            "gb_consumption_twh": gb_twh,
            "scotland_consumption_share": round(share_consumption, 4),
            "paid_in_scotland": round(scot_cost * share_consumption, 2),
            "paid_elsewhere": round(scot_cost * (1 - share_consumption), 2),
            "source": consumption_source,
            "source_url": consumption_url,
        },
        "turnup_same_window": _turnup(turnup_daily, start, end),
        "zone_source": "reference/bmu_zone.csv (Elexon BM unit register: grid zone per unit)",
    }


def _turnup(turnup_daily: pl.DataFrame | None, start, end) -> dict | None:
    if turnup_daily is None or not turnup_daily.height:
        return None
    w = turnup_daily.filter((pl.col("date") >= start) & (pl.col("date") <= end))
    if not w.height:
        return None
    return {"cost": round(float(w["cost_gbp"].sum()), 2),
            "to": w["date"].max().isoformat(), "basis": "replacement_estimate (GB-wide)"}
